print ('CS151 lab 0')
print ('Korede')
print ('I own a compound bow')
print ("I've been to texas before")
print ("I've made a stop motion video")
print ("I used to take care of a stray cat")
print ("I was born and raised in Baltimore")